### ISSUE TITLE
Error with unbonding LP staking

### ISSUE THREAD

**Issue by MarMiner** [ArableProtocol/bugs#2]
See screenshot. Doesn't work from the front-end. 
![error unstaking](https://user-images.githubusercontent.com/95941898/145645155-0dcdaa29-5c51-4b43-9ce1-5f590ca82547.png)

**Comment by hsouf** [comment]
There is a problem with **undelegate** function on Farming.sol contract (https://github.com/ArableProtocol/arablecontracts/blob/main/contracts/staking/Farming.sol):

``` solidity
if (_amount > 0) {
            address stakingLocker = factory.stakingLocker();

            pool.lpToken.approve(stakingLocker, _amount);
            IStakingLocker(stakingLocker).lockToken(
                address(pool.lpToken),
                msg.sender,
                _amount,
                block.timestamp,
                block.timestamp + pool.lockupDuration
            );
            user.amount = user.amount - _amount;
        }
```

when the user calls **undelegate()**, the transaction reverts with this error: "execution reverted: Not operator or owner" ==>returned by lockToken() function on StakingLocker smart contract. 
Maybe the address returned by factory.stakingLocker() is wrong. 
@gophereth

**Comment by hsouf** [comment]
There is a problem with **undelegate** function on Farming.sol contract (https://github.com/ArableProtocol/arablecontracts/blob/main/contracts/staking/Farming.sol):

``` solidity
if (_amount > 0) {
            address stakingLocker = factory.stakingLocker();

            pool.lpToken.approve(stakingLocker, _amount);
            IStakingLocker(stakingLocker).lockToken(
                address(pool.lpToken),
                msg.sender,
                _amount,
                block.timestamp,
                block.timestamp + pool.lockupDuration
            );
            user.amount = user.amount - _amount;
        }
```

when the user calls **undelegate()**, the transaction reverts with this error: "execution reverted: Not operator or owner" ==>returned by lockToken() function on StakingLocker smart contract. 
Maybe the address returned by factory.stakingLocker() is wrong. 
@gophereth

**Comment by gophereth** [comment]
This should be fixed on this PR
https://github.com/ArableProtocol/arablecontracts/pull/31

**Comment by gophereth** [comment]
This is temporarily fixed by @altbee by setting the farming contract to the operator of stakingLocker contract
