### ISSUE TITLE
Click to 'Connect wallet' w/o Metamask --> black screen

### ISSUE THREAD

**Issue by manjash** [ArableProtocol/bugs#4]
Steps to reproduce:
1. Use a browser (tried both Safari and Chrome) without Metamask extension installed 
2. Go to https://app.arablefi.com
3. Click 'Connect wallet' button
4. See a black screen

Expected:
See a screen recommending to install Metamask.

From the Console (if helps):
<img width="484" alt="image" src="https://user-images.githubusercontent.com/11697165/147789480-74c110cb-d93a-4171-baf4-b11748a06c7e.png">

**Comment by gophereth** [comment]
This issue will be handled

**Comment by gophereth** [comment]
Install metamask dialog is added on latest build
