### ISSUE TITLE
Incorrect amount in My Liquidity (ACRE-WAVAX Pool)

### ISSUE THREAD

**Issue by manjash** [ArableProtocol/bugs#6]
Issue:
1. I got 1.35709906991567253 PGL [Total PGL was 243,007.756907 (https://testnet.snowtrace.io/token/0x162cd559ea5440c02826f1f5cd10c8b7a1a1bf7e)] which is 5.5845915669064e-06 of the total PGL
2. With this for the $5,680,972.54 in pool liquidity I expect to have 5.5845915669064e-06 * $5,680,972.54 = 31.72591133871083 USD
3. Instead I have $45.53 in "My liquidity"

**Comment by gophereth** [comment]
@liccampanavd  can you check this issue and figure out the problem?

**Comment by liccampanavd** [comment]
@gophereth 

At the moment that I took the screenshot:

I got: 13,605 PGL
Total Supply: 348,042.300558 PGL
Total Liquidity: $7,630,317.81

count: 13,605 / 348,042.300558 * 7,630,317.81 = **298.28**

![Sin título](https://user-images.githubusercontent.com/76733810/148290735-035a0c0f-a4eb-4624-9d51-31cb2c5b9e65.png)

associated PR: https://github.com/ArableProtocol/arableapp/pull/178

**Comment by gophereth** [comment]
Ok, I will merge the PR and let's get confirmation from @manjash before closing the ticket.
New version is deployed on https://app.arablefi.com

**Comment by gophereth** [comment]
@manjash your bug report was invalid - we are turning back to original status.
Here pool liquidity is not total liquidity but liquidity that is bonded into the staking pool, not the total supply of token.

**Comment by Adricz22** [comment]
Hello @ArableProtocol 👋

# 🌍 Top International Developer Events

Discover the **most influential tech conferences and developer events** happening around the world.  
Connect, learn, and grow with the **global developer community**.

---

## 🚀 Why Join?
- 🔴 **Live Events** – Stay updated with the latest happenings in tech  
- 🌐 **Global Community** – Network with developers from all continents  
- 📅 **Updated Daily** – Fresh events, always current  
- 🏆 **Top 10 Developer Events** – Hand-picked to shape the future of technology  

From **cutting-edge frameworks** to **emerging paradigms**, we bring you the opportunities that matter.

---

## 🔑 Get Started  
**[➡️ Continue with GitHub](https://www.globaldevsummit.com/)**  
🔒 **Connect securely** • Save favorites • Get personalized recommendations  

---

## 📌 Highlights
- Meet industry leaders and tech innovators  
- Join exclusive technical workshops  
- Explore new frameworks, tools, and best practices  
- Grow your personal and professional network  

---

> 📢 **Tip:** Bookmark the page and check daily for new opportunities.  
Your next big career move could start here!

---
