### ISSUE TITLE
When staking, stake is active when the approval is not done yet 

### ISSUE THREAD

**Issue by manjash** [ArableProtocol/bugs#7]
Steps to reproduce:
1. Go to Pool folder
2. Try to Stake 5 ACRE
<img width="611" alt="image" src="https://user-images.githubusercontent.com/11697165/147890891-a3eea49c-85fe-4915-982c-bf8165d799f9.png">
3. See that 'Approve' button is inactive and 'Stake' is active

Expected:
1. First 'Approve' button should be active and 'Stake' - inactive
2. Then when approval is done, the 'Stake' is active and 'Approval' - not

**Comment by gophereth** [comment]
Thanks for the report, we will be working on it

**Comment by gophereth** [comment]
@liccampanavd we will need to check all the pages where same approval logic is available and fix all of those after check.

**Comment by liccampanavd** [comment]
@gophereth okay, I will check it all pages
